name: macOS

on: [workflow_dispatch, pull_request, push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_TYPE: Debug

jobs:
  build:
    name: ${{matrix.os}}-${{matrix.compiler.cc}}-${{matrix.type.label}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest]
        type:
          - { build_shared_libs: ON, label: shared}
          - { build_shared_libs: OFF, label: static}
        compiler:
          - {cc: clang, cxx: clang++}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Packages
        run: |
             brew install zstd uv boost fmt sdl2

      - name: Run CMake
        working-directory: ${{github.workspace}}
        env:
          CC: ${{ matrix.compiler.cc }}
          CXX: ${{ matrix.compiler.cxx }}
          CMAKE_PREFIX_PATH: /opt/homebrew
        run: |
             mkdir build
             cd build
             cmake .. -DBUILD_SHARED_LIBS=${{matrix.type.build_shared_libs}} -DCMAKE_BUILD_TYPE=Release -DBENCHMARK=ON

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: MAKEFLAGS=-j$(nproc) cmake --build .

      - name: Install
        working-directory: ${{github.workspace}}/build
        run: cmake --install . --prefix ../prefix

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ./test/sg_test
