name: MSYS2

on: [workflow_dispatch, pull_request, push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{matrix.config.sys}}
    runs-on: windows-latest
    timeout-minutes: 20
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { sys: clang64, CXXFLAGS: ""  }
          # We don't use these, as GCC (as of v14.10 on 02/2025) has a bug when using semaphores,
          # see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104928
          # - { sys: mingw64, CXXFLAGS: "" }
          # - { sys: ucrt64, CXXFLAGS: "" }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.config.sys}}
          update: true
          pacboy: toolchain:p cmake:p boost:p SDL2:p fmt:p libuv:p zstd:p graphviz:p doxygen:p

      - name: Run CMake
        working-directory: ${{github.workspace}}
        env:
          CXXFLAGS: ${{matrix.config.CXXFLAGS}}
        run: |
             mkdir build
             cd build
             # The Releae setting is a workaround vcpkg and
             # multi-release targets
             cmake .. -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=ON -DBENCHMARK=ON -DCMAKE_BUILD_TYPE=Release -DARCH_NATIVE=ON

      - name: Build
        working-directory: ${{github.workspace}}/build
        env:
          CXXFLAGS: ${{matrix.config.CXXFLAGS}}
        run: MAKEFLAGS=-j$(nproc) cmake --build .

      - name: Install
        working-directory: ${{github.workspace}}/build
        run: cmake --install . --prefix ../prefix

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ./test/sg_test.exe -d yes
        # ctest --output-on-failure
